### ISSUE TITLE
replace license

### ISSUE THREAD

**Issue by WarenGonzaga** [oss-ph/pinoy-made#7]
@jofftiquez it is good to replace the current license to fit it as a collection or list.
Let's use the same license used by Awesome List, which is CC0-1.0.

**Comment by jofftiquez** [comment]
> 

Sounds good to me, let's do it. Thanks.

**Comment by WarenGonzaga** [comment]
> > 
> 
> Sounds good to me, let's do it. Thanks.

Let's go! 😁

**Comment by WarenGonzaga** [comment]
All good @jofftiquez just review my PRs. #9 and #10

**Comment by WarenGonzaga** [comment]
Closing this now as per #9 has been merged.
